# My First Machine Learning with Scikit learn

##Pipeline concept(Titanic dataset)
###ทดลองเรียนรู้การใช้ ML ด้วย Scikit learn เพื่อวิเคราะห์หา Model 
ในการทำนายการรอดชีวิตของผู้โดยสารบนเรือไททานิค

In [36]:
from typing import Union, Any

from pandas import DataFrame, Series
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format='regina'

In [37]:
print(f'pandas version: {pd.__version__,}')
print(f'seaborn version: {sns.__version__}')

pandas version: ('1.5.3',)
seaborn version: 0.12.2


In [38]:
pd.Timestamp.now()

Timestamp('2023-09-30 09:47:15.386986')

In [39]:
# why this code chuck is error 
# Here I eliminate the non-keyboard character before 'url' to start the variable properly.
url = 'https://github.com/prasertcbs/basic-dataset/raw/master/titanic_train.csv'
df = pd.read_csv(url)
df.head()

PassengerId 
 Survived 
 Pclass 
 Name 
 Sex 
 Age 
 SibSp 
 Parch 
 Ticket 
 Fare 
 Cabin 
 Embarked 
 
 
 
 
 0 
 1 
 0 
 3 
 Braund, Mr. Owen Harris 
 male 
 22.0 
 1 
 0 
 A/5 21171 
 7.2500 
 NaN 
 S 
 
 
 1 
 2 
 1 
 1 
 Cumings, Mrs. John Bradley (Florence Briggs Th... 
 female 
 38.0 
 1 
 0 
 PC 17599 
 71.2833 
 C85 
 C 
 
 
 2 
 3 
 1 
 3 
 Heikkinen, Miss. Laina 
 female 
 26.0 
 0 
 0 
 STON/O2. 3101282 
 7.9250 
 NaN 
 S 
 
 
 3 
 4 
 1 
 1 
 Futrelle, Mrs. Jacques Heath (Lily May Peel) 
 female 
 35.0 
 1 
 0 
 113803 
 53.1000 
 C123 
 S 
 
 
 4 
 5 
 0 
 3 
 Allen, Mr. William Henry 
 male 
 35.0 
 0 
 0 
 373450 
 8.0500 
 NaN 
 S

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# Scikit-learn

In [41]:
# Why this code chuck is error 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split, cross_val_score, KFold, StratifiedKFold
# or whatever you want to import from sklearn.model_selection

#models
# Correct typo in the class name, it should be `KNeighborsClassifier` not `KNeighborsClsassifier`
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics

In [42]:
df[:3]

PassengerId 
 Survived 
 Pclass 
 Name 
 Sex 
 Age 
 SibSp 
 Parch 
 Ticket 
 Fare 
 Cabin 
 Embarked 
 
 
 
 
 0 
 1 
 0 
 3 
 Braund, Mr. Owen Harris 
 male 
 22.0 
 1 
 0 
 A/5 21171 
 7.2500 
 NaN 
 S 
 
 
 1 
 2 
 1 
 1 
 Cumings, Mrs. John Bradley (Florence Briggs Th... 
 female 
 38.0 
 1 
 0 
 PC 17599 
 71.2833 
 C85 
 C 
 
 
 2 
 3 
 1 
 3 
 Heikkinen, Miss. Laina 
 female 
 26.0 
 0 
 0 
 STON/O2. 3101282 
 7.9250 
 NaN 
 S

In [44]:
x:  = df[['Sex', 'Age', 'SibSp', 'Parch', 'Pclass']]
y = df.Survived

In [45]:
# why this code cannot plot histogram graph 
# Before plotting the histogram, let's check and handle null values in 'Age' column
if df['Age'].isnull().sum() > 0:
    print(f"There are {df['Age'].isnull().sum()} null values in 'Age'. Replacing with median...")
    df['Age'].fillna(df['Age'].median(), inplace=True)

df['Age'].hist()


There are 177 null values in 'Age'. Replacing with median...


<Axes: >

<Figure size 640x480 with 1 Axes>

In [46]:
col_trans = make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)
col_trans

ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'), ['Age']),
 ('onehotencoder', OneHotEncoder(), ['Sex'])]) In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org. ColumnTransformer ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'), ['Age']),
 ('onehotencoder', OneHotEncoder(), ['Sex'])]) simpleimputer ['Age'] SimpleImputer SimpleImputer(strategy='median') onehotencoder ['Sex'] OneHotEncoder OneHotEncoder() remainder passthrough passthrough

In [47]:
model = KNeighborsClassifier()

In [48]:
pipe = make_pipeline(col_trans, model)
pipe

Pipeline(steps=[('columntransformer',
 ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'),
 ['Age']),
 ('onehotencoder',
 OneHotEncoder(), ['Sex'])])),
 ('kneighborsclassifier', KNeighborsClassifier())]) In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org. Pipeline Pipeline(steps=[('columntransformer',
 ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'),
 ['Age']),
 ('onehotencoder',
 OneHotEncoder(), ['Sex'])])),
 ('kneighborsclassifier', KNeighborsClassifier())]) columntransformer: ColumnTransformer ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'), ['Age']),
 ('onehotencoder', OneHotEncoder(), ['Sex'])]) simpleimputer ['Age'] SimpleImputer SimpleImputer(strategy='median') onehotencoder ['Sex'] OneHotEncoder OneHotEncoder() remainder passthrough passthrough KNeighborsClassifier KNeighborsClassifier()

In [49]:
accuracy = cross_val_score(pipe, x, y, cv=10)
print(accuracy)
print(f'accuracy mean {accuracy.mean()}')

[0.74444444 0.84269663 0.74157303 0.85393258 0.82022472 0.7752809
 0.87640449 0.79775281 0.84269663 0.80898876]
accuracy mean 0.8103995006242197


In [50]:
col_trans = make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)
col_trans

for k in range(5, 15):
    model = KNeighborsClassifier(n_neighbors=k)
    pipe = make_pipeline(col_trans, model)
    accuracy = cross_val_score(pipe, x, y, cv=10)
    print(f'n_neighbors = {k:02}: accuracy = {accuracy.mean():.4f}')


n_neighbors = 05: accuracy = 0.8104
n_neighbors = 06: accuracy = 0.8048
n_neighbors = 07: accuracy = 0.8149
n_neighbors = 08: accuracy = 0.8194
n_neighbors = 09: accuracy = 0.8249
n_neighbors = 10: accuracy = 0.8093
n_neighbors = 11: accuracy = 0.8137
n_neighbors = 12: accuracy = 0.7924
n_neighbors = 13: accuracy = 0.7981
n_neighbors = 14: accuracy = 0.7935


In [63]:
# teach me correct this code chuck to run 
# Replacement for the last cell
col_trans = make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)
col_trans

#Here I would suggest using a range from, say, 100 to 200 for n_estimators to obtain more reasonable classification results.
for k in range(100, 200, 10):
    model = RandomForestClassifier(n_estimators=k)
    pipe = make_pipeline(col_trans, model)
    accuracy = cross_val_score(pipe, x, y, cv=10)
    print(f'n_estimators = {k:02}: accuracy = {accuracy.mean():.4f}')

n_estimators = 100: accuracy = 0.8093
n_estimators = 110: accuracy = 0.8082
n_estimators = 120: accuracy = 0.8082
n_estimators = 130: accuracy = 0.8059
n_estimators = 140: accuracy = 0.8059
n_estimators = 150: accuracy = 0.8037
n_estimators = 160: accuracy = 0.8115
n_estimators = 170: accuracy = 0.8003
n_estimators = 180: accuracy = 0.8070
n_estimators = 190: accuracy = 0.8071


In [72]:
# teach me correct this code chuck to run  
col_trans=make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)
model = KNeighborsClassifier(n_neighbors=7)
pipe=make_pipeline(col_trans, model)

# Fit the model using training data
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
 ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'),
 ['Age']),
 ('onehotencoder',
 OneHotEncoder(), ['Sex'])])),
 ('kneighborsclassifier', KNeighborsClassifier(n_neighbors=7))]) In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org. Pipeline Pipeline(steps=[('columntransformer',
 ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'),
 ['Age']),
 ('onehotencoder',
 OneHotEncoder(), ['Sex'])])),
 ('kneighborsclassifier', KNeighborsClassifier(n_neighbors=7))]) columntransformer: ColumnTransformer ColumnTransformer(remainder='passthrough',
 transformers=[('simpleimputer',
 SimpleImputer(strategy='median'), ['Age']),
 ('onehotencoder', OneHotEncoder(), ['Sex'])]) simpleimputer ['Age'] SimpleImputer SimpleImputer(strategy='median') onehotencoder ['Sex'] OneHotEncoder OneHotEncoder() remainder ['SibSp', 'Parch', 'Pclass'] passthrough passthrough KNeighborsClassifier KNeighborsClassifier(n_neighbors=7)

In [80]:
# teach me correct this code chuck to run   
# First define the data subsets: x_train, x_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, stratify=y)

# Now we create the column transformer for preprocessing
col_trans = make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)

# Define the model
model = KNeighborsClassifier(n_neighbors=7)

#Create a pipeline
pipe = make_pipeline(col_trans, model)

# Fit the model using training data
pipe.fit(x_train, y_train)

# Display score
pipe.score(x_test, y_test)

0.7932960893854749

In [83]:
# how can i check varian X in this model 
# First define the data subsets: x_train, x_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, stratify=y)

# Now we create the column transformer for preprocessing
col_trans = make_column_transformer(
    (SimpleImputer(strategy='median'), ['Age']),
    (OneHotEncoder(), ['Sex']),
    remainder='passthrough'
)

# Define the model
model = KNeighborsClassifier(n_neighbors=7)

#Create a pipeline
pipe = make_pipeline(col_trans, model)

# Fit the model using training data
pipe.fit(x_train, y_train)

# Display score
print("Test Score: ", pipe.score(x_test, y_test))

# Transform x_test using the pipeline
transformed_x_test = pipe.named_steps['columntransformer'].transform(x_test)

print("Transformed x_test: ")
print(transformed_x_test)

Test Score:  0.8212290502793296
Transformed x_test: 
[[ 1.  0.  1.  5.  2.  3.]
 [28.  0.  1.  0.  0.  3.]
 [28.  0.  1.  0.  0.  1.]
 ...
 [39.  1.  0.  1.  1.  1.]
 [51.  0.  1.  0.  0.  3.]
 [36.  1.  0.  0.  2.  1.]]


In [84]:
x_new=pd.DataFrame(
{
        'Sex': ['male', 'female'],
        'Age': [25, 20],
        'SibSp' : [1,2],
        'Parch': [0,0],
        'Pclass': [1,3]
})
x_new

Sex 
 Age 
 SibSp 
 Parch 
 Pclass 
 
 
 
 
 0 
 male 
 25 
 1 
 0 
 1 
 
 
 1 
 female 
 20 
 2 
 0 
 3

In [85]:
pipe.predict(x_new)

array([0, 1])

In [86]:
pipe.predict_proba(x_new)

array([[0.57142857, 0.42857143],
 [0.42857143, 0.57142857]])

In [88]:
predicted=pipe.predict(x_test)
predicted

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
 1, 0, 1])

In [89]:
metrics.confusion_matrix(y_test, predicted)

array([[93, 17],
 [15, 54]])

In [90]:
metrics.accuracy_score(y_test, predicted)

0.8212290502793296

In [92]:
print(metrics.classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       0.86      0.85      0.85       110
           1       0.76      0.78      0.77        69

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179



In [95]:
93/(93+15)

0.8611111111111112

In [97]:
54/(17+54)

0.7605633802816901

In [98]:
93/(93+17)

0.8454545454545455

In [99]:
54/(54+15)

0.782608695652174